services:
  _defaults:
    public: true

  # Repository
  PrestaShop\Module\PersonalSalesmen\Repository\AssignmentRepository:
    class: PrestaShop\Module\PersonalSalesmen\Repository\AssignmentRepository

  # Services
  PrestaShop\Module\PersonalSalesmen\Service\AccessControlService:
    class: PrestaShop\Module\PersonalSalesmen\Service\AccessControlService
    arguments:
      - '@prestashop.adapter.legacy.context'

  PrestaShop\Module\PersonalSalesmen\Service\AssignmentService:
    class: PrestaShop\Module\PersonalSalesmen\Service\AssignmentService
    arguments:
      - '@PrestaShop\Module\PersonalSalesmen\Repository\AssignmentRepository'